Repository woodpecker-ci/helm, pull requests merged in 2023-10, with the labels that each got.

#82 Add renovate config and set image versions in workflows
  .woodpecker/release-helper.yml
  .woodpecker/release.yml
  .woodpecker/test.yml
  renovate.json
Labels: chore 🧰

#83 Publish chart to OCI registry (alongside gh-pages)
  .woodpecker/release.yml
  README.md
Labels: enhancement 👆️

#91 Align README template with current state
  README-main.md.gotmpl
  README.md
  charts/agent/README.md
Labels: documentation 📖️

#95 Correct username for docker login
  .woodpecker/release.yml
Labels: bug 🐛️

#90 Remove dind
  charts/agent/README.md
  charts/agent/templates/deployment.yaml
  charts/agent/values.yaml
  values.yaml
Labels: breaking

#98 Correctly condition `volumeMounts`
  charts/server/templates/statefulset.yaml
Labels: bug 🐛️

#94 feat(woodpecker-server)!: add monitoring resources and other improvements
  Chart.lock
  Chart.yaml
  README-main.md.gotmpl
  README.md
  charts/agent/README.md
  charts/agent/templates/deployment.yaml
  charts/server/Chart.yaml
  charts/server/README.md
  charts/server/README.md.gotmpl
  charts/server/grafana_dashboards/.gitkeep
  charts/server/templates/configmap_grafana_dashboards.yaml
  charts/server/templates/ingress.yaml
  charts/server/templates/pod-monitor.yaml
  charts/server/templates/prometheus-rules.yaml
  charts/server/templates/service-headless.yaml
  charts/server/templates/service.yaml
  charts/server/templates/statefulset.yaml
  charts/server/values.yaml
Labels: feature 🚀️, major

#104 fix: use named port on ingress
  charts/server/templates/ingress.yaml
Labels: skip-changelog
