Repository woodpecker-ci/helm, pull requests merged in 2023-08, with the labels that each got.

#56 no unshallow
  .woodpecker/test.yml
Labels: chore 🧰

#61 Fix test workflow for tags
  .woodpecker/test.yml
Labels: bug 🐛️

#47 Add extraVolumes and extraVolumeMounts
  README.md
  charts/agent/templates/deployment.yaml
  charts/agent/values.yaml
Labels: feature 🚀️

#59 feature: add custom command
  charts/agent/templates/deployment.yaml
  charts/agent/values.yaml
  charts/server/templates/statefulset.yaml
  charts/server/values.yaml
Labels: feature 🚀️
