Repository woodpecker-ci/helm, pull requests merged in 2023-09, with the labels that each got.

#68 Fix release
  .woodpecker/release.yml
Labels: chore 🧰

#60 Improve `helm-docs` invocation and clean templates
  .woodpecker/release-helper.yml
  .woodpecker/release.yml
  Makefile
  README-main.md.gotmpl
  README.md
  README.md.gotmpl
Labels: documentation 📖️

#70 Fix missing `image.registry` for agent
  charts/agent/templates/deployment.yaml
  charts/agent/values.yaml
Labels: bug 🐛️

#78 add documentation for extra volume mounts in agent
  charts/agent/values.yaml
  values.yaml
Labels: documentation 📖️
