Repository woodpecker-ci/helm, pull requests merged in 2023-11, with the labels that each got.

#121 Add `helm-unittests` skeleton and assert `extraVolumes` and `extraVolumeMounts`
  .woodpecker/test.yml
  Makefile
  charts/woodpecker/charts/server/unittests/statefulset/volumes.yaml
  renovate.json
Labels: chore 🧰

#125 Release config: update subchart app versions via renovate, comment behavior
  charts/woodpecker/Chart.yaml
  charts/woodpecker/charts/agent/Chart.yaml
  charts/woodpecker/charts/server/Chart.yaml
  release-config.ts
  renovate.json
Labels: skip-changelog, chore 🧰

#129 Update to main branch for release
  .woodpecker/release.yml
Labels: build

#128 Use dynamic badges
  README.md
  charts/woodpecker/charts/agent/README.md
  charts/woodpecker/charts/server/README.md
Labels: documentation 📖️

#103 chore: speedup make docs (add README.md.gotmpl to charts/agent)
  Makefile
Labels: chore 🧰
