Repository woodpecker-ci/helm, pull requests merged in 2024-09, with the labels that each got.

#219 Fix env var parsing
  .woodpecker/test.yml
Labels: build

#221 Fix release config
  release-config.ts
Labels: build

#223 Support separate namespace for pipeline pods
  charts/woodpecker/Chart.lock
  charts/woodpecker/Chart.yaml
  charts/woodpecker/charts/agent/Chart.yaml
  charts/woodpecker/charts/agent/templates/role.yaml
  charts/woodpecker/charts/agent/templates/rolebinding.yaml
Labels: feature 🚀️

#224 Remove uneeded agent role rules
  charts/woodpecker/charts/agent/templates/role.yaml
Labels: enhancement 👆️
