Repository woodpecker-ci/helm, pull requests merged in 2024-11, with the labels that each got.

#242 Fix ghcr login
  .woodpecker/release.yml
Labels: bug 🐛️, build

#228 Auto-create `WOODPECKER_AGENT_SECRET` secret
  charts/woodpecker/Chart.lock
  charts/woodpecker/Chart.yaml
  charts/woodpecker/README.md
  charts/woodpecker/charts/agent/Chart.yaml
  charts/woodpecker/charts/agent/README.md
  charts/woodpecker/charts/agent/README.md.gotmpl
  charts/woodpecker/charts/agent/templates/statefulset.yaml
  charts/woodpecker/charts/agent/values.yaml
  charts/woodpecker/charts/server/Chart.yaml
  charts/woodpecker/charts/server/README.md
  charts/woodpecker/charts/server/README.md.gotmpl
  charts/woodpecker/charts/server/templates/secret.yaml
  charts/woodpecker/charts/server/templates/statefulset.yaml
  charts/woodpecker/charts/server/unittests/statefulset/__snapshot__/secrets.yaml.snap
  charts/woodpecker/charts/server/unittests/statefulset/secrets.yaml
  charts/woodpecker/charts/server/values.yaml
  charts/woodpecker/values.yaml
Labels: feature 🚀️, breaking

#246 fix(server): add group name of prometheus-rules
  charts/woodpecker/charts/server/templates/prometheus-rules.yaml
Labels: enhancement 👆️

#253 chore: format via prettier
  .editorconfig-checker.json
  .pre-commit-config.yaml
  .prettierignore
  .woodpecker/lint.yaml
  charts/woodpecker/README.md
  charts/woodpecker/charts/agent/README.md
  charts/woodpecker/charts/server/README.md
Labels: chore 🧰

#254 Optimize README
  README.md
Labels: documentation 📖️

#256 Refine CODEOWNER
  CODEOWNERS
Labels: chore 🧰

#257 fix: update tarball output dir
  .woodpecker/release.yml
Labels: build

#258 Remove custom package rules and config
  renovate.json
Labels: build

#265 fix: run prettier after README update
  .woodpecker/release.yml
Labels: build

#263 server/templates/secret: fix extra chomper breaking secret templating
  charts/woodpecker/charts/server/templates/secret.yaml
Labels: bug 🐛️
