Repository woodpecker-ci/helm, pull requests merged in 2025-01, with the labels that each got.

#288 Set default `securityContext`
  charts/woodpecker/Chart.lock
  charts/woodpecker/Chart.yaml
  charts/woodpecker/README.md
  charts/woodpecker/charts/agent/Chart.yaml
  charts/woodpecker/charts/agent/README.md
  charts/woodpecker/charts/agent/values.yaml
  charts/woodpecker/charts/server/Chart.yaml
  charts/woodpecker/charts/server/README.md
  charts/woodpecker/charts/server/values.yaml
Labels: feature 🚀️

#301 bump chart versions and add migration notes
  charts/woodpecker/Chart.lock
  charts/woodpecker/Chart.yaml
  charts/woodpecker/README.md
  charts/woodpecker/README.md.gotmpl
  charts/woodpecker/charts/agent/Chart.yaml
  charts/woodpecker/charts/agent/README.md
  charts/woodpecker/charts/agent/README.md.gotmpl
  charts/woodpecker/charts/server/Chart.yaml
  charts/woodpecker/charts/server/README.md
  charts/woodpecker/charts/server/README.md.gotmpl
Labels: chore 🧰

#307 Also set the default file system group Security Context
  charts/woodpecker/charts/agent/values.yaml
  charts/woodpecker/charts/server/values.yaml
Labels: bug 🐛️
